{
    'name': 'Instituto',
    'version': '1.0',
    'category': 'Education',
    'summary': 'Gestión de alumnado, empresas y tutorías FCT',
    'sequence': 10,
    'license': 'AGPL-3',
    'author': 'Marcos Vazquez',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/menu_principal.xml',
        'views/tutoriafct/tutoriafct_view.xml',
        'views/tutoriafct/menu.xml',
        'views/alumnado/alumnado_view.xml',
        'views/alumnado/menu.xml',
        'views/empresa/empresa_view.xml',
        'views/empresa/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}